# Software License Agreement (proprietary) 
#
# @author    Arnold <akalmbach@clearpathrobotics.com>
# @copyright (c) 2014, Clearpath Robotics, Inc., All rights reserved.
#
# Redistribution and use in source and binary forms, with or without modification, is not permitted without the
# express permission of Clearpath Robotics.
#autogenerated by ROS python message generators
