joint_limits:
  arm_1_joint:
    has_position_limits: true
    min_position: -3.08
    max_position: 3.08
    has_velocity_limits: true
    min_position_hard: -3.13
    max_position_hard: 3.13
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.025
    angle_wraparound: false
  arm_2_joint:
    has_position_limits: true
    min_position: -1.51
    max_position: 1.51
    min_position_hard: -1.56
    max_position_hard: 1.56
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.025
    angle_wraparound: false
  arm_3_joint:
    has_position_limits: true
    min_position: -3.08
    max_position: 3.08
    min_position_hard: -3.13
    max_position_hard: 3.13
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.025
    angle_wraparound: false
  arm_4_joint:
    has_position_limits: true
    min_position: -2.17
    max_position: 2.17
    min_position_hard: -2.12
    max_position_hard: 2.12
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.025
    angle_wraparound: false
  arm_5_joint:
    has_position_limits: true
    min_position: -3.08
    max_position: 3.08
    min_position_hard: -3.13
    max_position_hard: 3.13
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.025
    angle_wraparound: false
  arm_6_joint:
    has_position_limits: true
    min_position: -1.75
    max_position: 1.52
    min_position_hard: -1.80
    max_position_hard: 1.57 
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.025
    angle_wraparound: false
  arm_7_joint:
    has_position_limits: true
    min_position: -2.88
    max_position: 2.88
    min_position_hard: -2.93
    max_position_hard: 2.93
    has_velocity_limits: true
    max_velocity: 0.4
    has_acceleration_limits: true
    max_acceleration: 0.025
    angle_wraparound: false
  joint_front_right_wheel:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  joint_front_left_wheel:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  joint_back_right_wheel:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
  joint_back_left_wheel:
    has_velocity_limits: true
    max_velocity: 100
    has_acceleration_limits: false
    max_acceleration: 0
